/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.laberinto_grupo2;

import com.mycompany.laberinto_grupo2.GestorPartidas;
import com.mycompany.laberinto_grupo2.Juego;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.*;


/**
 *
 * @author masalgue
 */
public class RegistroJugador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroJugador.class.getName());
    private String nombreJugador = "";
    private boolean continuarPartida = false;
    /**
     * Creates new form RegistroJugador
     */
    public RegistroJugador() {
        initComponents();
        verificarPartidaGuardada();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblGrupo = new javax.swing.JLabel();
        lblRamirez = new javax.swing.JLabel();
        lblGomez = new javax.swing.JLabel();
        lblSalguero = new javax.swing.JLabel();
        lblRosales = new javax.swing.JLabel();
        lblSanchez = new javax.swing.JLabel();
        panelPartidaGuardada = new javax.swing.JPanel();
        lblInfoPartida = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        btnNuevaPartida = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(450, 350));

        jPanel1.setPreferredSize(new java.awt.Dimension(360, 359));

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblTitulo.setText("Juego de Laberinto Interactivo en Java con Swing");

        lblGrupo.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblGrupo.setText("GRUPO #2");

        lblRamirez.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblRamirez.setText("Ramírez Meneses Edwin Yohan");

        lblGomez.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblGomez.setText("Gómez Bermeo Carlos Luis");

        lblSalguero.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblSalguero.setText("Mario Alexander Salguero Castillo");

        lblRosales.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblRosales.setText("Ariel Rosales Borbor William");

        lblSanchez.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblSanchez.setText("Eliat Moisés Sánchez Benalcázar");

        panelPartidaGuardada.setLayout(null);
        panelPartidaGuardada.setBounds(25, 60, 400, 120);
        panelPartidaGuardada.setVisible(false);
        panelPartidaGuardada.setBackground(new java.awt.Color(255, 255, 220));

        lblInfoPartida.setText("txt");
        lblInfoPartida.setBounds(10, 10, 380, 60);
        panelPartidaGuardada.add(lblInfoPartida);

        btnContinuar.setBackground(new java.awt.Color(34, 139, 34));
        btnContinuar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(0, 0, 0));
        btnContinuar.setText("CONTINUAR PARTIDA");
        btnContinuar.setFocusPainted(false);
        btnContinuar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnContinuar.addActionListener(this::btnContinuarActionPerformed);

        btnNuevaPartida.setBackground(new java.awt.Color(70, 130, 180));
        btnNuevaPartida.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNuevaPartida.setForeground(new java.awt.Color(0, 0, 0));
        btnNuevaPartida.setText("NUEVA PARTIDA");
        btnNuevaPartida.setFocusPainted(false);
        btnNuevaPartida.setCursor(new Cursor(Cursor.HAND_CURSOR));
        // btnNuevaPartida.addActionListener(e -> mostrarFormularioNuevaPartida());
        btnNuevaPartida.addActionListener(this::btnNuevaPartidaActionPerformed);

        javax.swing.GroupLayout panelPartidaGuardadaLayout = new javax.swing.GroupLayout(panelPartidaGuardada);
        panelPartidaGuardada.setLayout(panelPartidaGuardadaLayout);
        panelPartidaGuardadaLayout.setHorizontalGroup(
            panelPartidaGuardadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPartidaGuardadaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelPartidaGuardadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPartidaGuardadaLayout.createSequentialGroup()
                        .addComponent(lblInfoPartida)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelPartidaGuardadaLayout.createSequentialGroup()
                        .addComponent(btnContinuar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(btnNuevaPartida)
                        .addGap(42, 42, 42))))
        );
        panelPartidaGuardadaLayout.setVerticalGroup(
            panelPartidaGuardadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPartidaGuardadaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfoPartida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(panelPartidaGuardadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContinuar)
                    .addComponent(btnNuevaPartida))
                .addGap(16, 16, 16))
        );

        lblNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNombre.setText("Ingresa tu nombre:");

        btnIniciar.setBackground(new java.awt.Color(255, 153, 51));
        btnIniciar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(0, 0, 0));
        btnIniciar.setText("INICIAR JUEGO");
        btnIniciar.addActionListener(this::btnIniciarActionPerformed);

        txtNombre.setToolTipText("Escribe tu nombre aquí");
        txtNombre.addActionListener(evt -> iniciarNuevaPartida());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(lblGrupo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRamirez)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblGomez))))
                            .addComponent(lblSalguero)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblRosales))
                            .addComponent(lblSanchez)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelPartidaGuardada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnIniciar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGrupo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRamirez)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGomez)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSalguero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRosales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSanchez)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(panelPartidaGuardada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIniciar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNombre)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        continuarPartidaGuardada();
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        iniciarNuevaPartida();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnNuevaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaPartidaActionPerformed
        mostrarFormularioNuevaPartida();
    }//GEN-LAST:event_btnNuevaPartidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistroJugador().setVisible(true));
    }
    /**
     * Verifica si existe una partida guardada y muestra las opciones correspondientes
     */
    private void verificarPartidaGuardada() {
        if (GestorPartidas.existePartidaGuardada()) {
            String[] datos = GestorPartidas.cargarPartida();
            if (datos != null && datos[0] != null) {
                // Mostrar panel de partida guardada
                panelPartidaGuardada.setVisible(true);
                
                String info = "<html>" +
                              "Se encontró una partida guardada:<br>" +
                              "<b>Jugador:</b> " + datos[0] + "<br>" +
                              "<b>Nivel:</b> " + datos[1] + " | " +
                              "<b>Puntaje:</b> " + datos[2] +
                              "</html>";
                lblInfoPartida.setText(info);
                
                // Ocultar campos de nueva partida inicialmente
                lblNombre.setVisible(false);
                txtNombre.setVisible(false);
                btnIniciar.setVisible(false);
            }
        } else {
            // No hay partida guardada, mostrar formulario normal
            panelPartidaGuardada.setVisible(false);
            lblNombre.setVisible(true);
            txtNombre.setVisible(true);
            btnIniciar.setVisible(true);
        }
    }
    
    /**
     * Continúa con la partida guardada
     */
    private void continuarPartidaGuardada() {
        String[] datos = GestorPartidas.cargarPartida();
        if (datos != null) {
            nombreJugador = datos[0];
            int nivelGuardado = Integer.parseInt(datos[1]);
            int puntajeGuardado = Integer.parseInt(datos[2]);
            
            continuarPartida = true;
            
            // Cerrar ventana de registro
            this.dispose();
            
            // Iniciar el juego con los datos guardados
            iniciarJuego(nombreJugador, nivelGuardado, puntajeGuardado);
        }
    }
    
    /**
     * Muestra el formulario para iniciar una nueva partida
     */
    private void mostrarFormularioNuevaPartida() {
        int respuesta = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de que deseas iniciar una nueva partida?\n" +
            "Se perderá el progreso de la partida guardada.",
            "Nueva Partida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        
        if (respuesta == JOptionPane.YES_OPTION) {
            // Eliminar partida guardada
            GestorPartidas.eliminarPartidaGuardada();
            
            // Mostrar formulario de nueva partida
            panelPartidaGuardada.setVisible(false);
            lblNombre.setVisible(true);
            txtNombre.setVisible(true);
            btnIniciar.setVisible(true);
            txtNombre.requestFocus();
        }
    }
    
    /**
     * Inicia una nueva partida desde cero
     */
    private void iniciarNuevaPartida() {
        nombreJugador = txtNombre.getText().trim();
        
        if (nombreJugador.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Por favor ingresa tu nombre", 
                "Nombre requerido", 
                JOptionPane.WARNING_MESSAGE);
            txtNombre.requestFocus();
            return;
        }
        
        continuarPartida = false;
        
        // Cerrar ventana de registro
        this.dispose();
        
        // Iniciar el juego desde el nivel 1
        iniciarJuego(nombreJugador, 1, 0);
    }
    
    /**
     * Inicia el juego con los parámetros especificados
     */
    private void iniciarJuego(String nombre, int nivelInicial, int puntajeInicial) {
        JFrame miVentana = new JFrame("Laberinto Beta - " + nombre);
        Juego game = new Juego(nombre, nivelInicial, puntajeInicial);
        miVentana.add(game);
        miVentana.setSize(920, 540);
        miVentana.setLocation(300, 200);
        miVentana.setVisible(true);
        miVentana.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        // Agregar listener para guardar al cerrar
        miVentana.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                // Guardar partida al cerrar
                if (Juego.obtieneNivel() <= 10) {
                    GestorPartidas.guardarPartida(
                        nombre, 
                        Juego.obtieneNivel(), 
                        Juego.obtienePuntaje()
                    );
                }
            }
        });
        
        // Loop del juego
        new Thread(() -> {
            while (true) {
                try {
                    Thread.sleep(10);
                } catch (InterruptedException ex) {
                    ex.printStackTrace();
                }
                game.repaint();
                
                if (Juego.obtieneNivel() > 10) {
                    // Eliminar partida guardada al completar el juego
                    GestorPartidas.eliminarPartidaGuardada();
                    
                    JOptionPane.showMessageDialog(null, 
                        "¡FELICIDADES " + nombre.toUpperCase() + "!\n\n" +
                        "Has completado los 10 niveles del laberinto\n" +
                        "Puntaje Final: " + Juego.obtienePuntaje() + " puntos\n\n" +
                        "¡Eres un maestro del laberinto!");
                    System.exit(0);
                }
            }
        }).start();
    }
    
    public String getNombreJugador() {
        return nombreJugador;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnNuevaPartida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblGomez;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblInfoPartida;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRamirez;
    private javax.swing.JLabel lblRosales;
    private javax.swing.JLabel lblSalguero;
    private javax.swing.JLabel lblSanchez;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelPartidaGuardada;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
